### ISSUE TITLE
Connection Issues with Specific Plugin Versions on Bungeecord Network

### ISSUE THREAD

**Issue by amatheo** [SpielefreakJ/VersionControl#1]
I've been using this plugin successfully for some time on my Bungeecord network. 
However, recently I've encountered an issue when attempting to set it up again with newer versions. The main problem arises when trying to connect using the specified versions within the config file.

**Plugin Version**: 1.3.4
**Bungeecord Version**: 1.20-R0.3-SNAPSHOT
**ViaVersion & ViaBackwards**: 4.10.0

### Steps to Reproduce

1. Set up the plugin with the initial configurations.
2. Modify config.yml to match the new versions as follows 
``` yaml
Server:
  Fallback: kick
  vibing:
    minVersion: '735'
    maxVersion: '765'

...
```
3. Trying to connect with Vanilla Client 1.20.4

### Observed Behavior

Connections cannot be established using the specified version range. Setting the minVersion and maxVersion to -1 does allow connections, but it removes the version restrictions, enabling all versions to connect, which defeats the purpose of the plugin.

### Temporary Fix
Currently, the only workaround is to set the version in config.yml to -1, which is not ideal as it allows any client version to connect:
``` yaml
Server:
  Fallback: kick
  vibing:
    minVersion: '-1'
    maxVersion: '-1'

...

Versions:
  '-1': test
```

### Possible Cause

I suspect that changes in the ViaAPI can be attributed to this issue
